# Usamos una imagen de Node.js para construir el frontend
FROM node:20-alpine

# Establecer el directorio de trabajo
RUN mkdir -p /usr/src/app &&\
 chown -R node:node /usr/src/app
WORKDIR /usr/src/app

RUN chgrp -R 0 /usr/src/app &&\
 chmod -R g+rwX /usr/src/app

# Copiar los archivos de package.json y package-lock.json
COPY package*.json /usr/src/app

USER 1000

# Instalar dependencias
RUN npm install

# Copiar el resto de los archivos del proyecto
COPY --chown=node:node . /usr/src/app

# Exponer el puerto en el que correrá la aplicación Nuxt
EXPOSE 3000

# Comando por defecto para ejecutar la aplicación en modo desarrollo
CMD ["npm, "run", "dev"]


